### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by blink1073** [rgbkrk/jupyter-sidecar#2]
Thanks for making this!  I was trying to install it, as I'm looking to make something similar to the QtConsole, but using Javascript.  However, when I try to run the app, I get this error.  The same thing happened on OSX and Ubuntu 12.04 64bit.  Any ideas?

```bash
$ electron . /Users/ssilvester//.ipython/profile_default/security/kernel-55141.json
App threw an error when running [Error: Module version mismatch. Expected 44, got 43.]
```

![screen shot 2015-06-16 at 8 59 59 am](https://cloud.githubusercontent.com/assets/2096628/8184809/21b213ea-1406-11e5-9e4e-8d6185d3450e.png)

**Comment by blink1073** [comment]
If I remove `node_modules`, run `npm update`, and then run the `zmq` rebuild, I get the same error, but `got 11` instead of 43.

**Comment by blink1073** [comment]
```bash
ssilvester: ~/workspace/jupyter-sidecar (master) 0
$ npm -v
2.10.1
```

**Comment by rgbkrk** [comment]
Wow that is just the ugliest error. What's your default Python?

**Comment by rgbkrk** [comment]
Also, thanks for taking this package for a spin. It's not ready for prime time and I've been working in (and using) a different branch.

**Comment by rgbkrk** [comment]
I've been using iojs (which is also the node used inside of electron). I think we'll have to build native extensions using the same version...

With a fresh checkout, I'm getting a hairy error as well:

```
$ electron . ~/Library/Jupyter/runtime/kernel-39794.json
dyld: lazy symbol binding failed: Symbol not found: __ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEEiPS5_
  Referenced from: /Users/kyle6475/jupyter-sidecar/node_modules/zmq/build/Release/zmq.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEEiPS5_
  Referenced from: /Users/kyle6475/jupyter-sidecar/node_modules/zmq/build/Release/zmq.node
  Expected in: dynamic lookup

/usr/local/bin/electron: line 2: 41722 Trace/BPT trap: 5       "/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron" "$@"
```

**Comment by blink1073** [comment]
```bash
$ python -V
Python 2.7.6
```
I had originally tried with my default 3.4, and ran into the `node-gyp` problem.

**Comment by blink1073** [comment]
Should I try from the `kernel_watch` branch?

**Comment by rgbkrk** [comment]
Yeah, though I'm finding there must be a strange set of incantations I performed.

**Comment by blink1073** [comment]
Yeah I'm finding `npm` hell to be worse than the old `setuptools` days...

**Comment by blink1073** [comment]
Yikes!

![screen shot 2015-06-16 at 10 23 25 am](https://cloud.githubusercontent.com/assets/2096628/8186745/c2176154-1411-11e5-9b06-41949f8c9bb8.png)

**Comment by rgbkrk** [comment]
I'm digging on this now. Relatedly, I'd like to start making ports of basic Jupyter functionality in the https://github.com/nteract org. Primarily that's in https://github.com/nteract/jupyter-paths with the current plan of attack being https://github.com/nteract/jupyter-paths/issues/1.

**Comment by rgbkrk** [comment]
Here's [the electron doc](http://electron.atom.io/docs/v0.27.0/tutorial/using-native-node-modules/) I went through before.

**Comment by blink1073** [comment]
The problems persist...

**Comment by rgbkrk** [comment]
After #3, seems like we're right on task and with #5 it's getting simpler.
